services:
  astroneer:
    build:
      context: .
      tags:
        - whalybird/astroneer-server:latest
    stdin_open: true
    tty: true
    ports:
      - 7777:7777/udp
    volumes:
      - ./saved:/astrotux/AstroneerServer/Astro/Saved
      # - ./launcher.toml:/astrotux/launcher.toml
